export const QUESTIONS = [
  { domain: 'Demandas Quantitativas', text: 'O seu trabalho exige que você trabalhe muito rápido?', inverted: true },
  { domain: 'Demandas Quantitativas', text: 'Você tem muito trabalho a fazer?', inverted: true },
  { domain: 'Demandas Quantitativas', text: 'O seu trabalho exige muita concentração?', inverted: true },
  { domain: 'Demandas Quantitativas', text: 'Você precisa realizar várias tarefas ao mesmo tempo?', inverted: true },
  { domain: 'Demandas Cognitivas', text: 'O seu trabalho exige que você tome decisões difíceis?', inverted: true },
  { domain: 'Demandas Cognitivas', text: 'É necessário pensar em muitas coisas ao mesmo tempo?', inverted: true },
  { domain: 'Demandas Cognitivas', text: 'O seu trabalho exige muita criatividade?', inverted: true },
  { domain: 'Demandas Cognitivas', text: 'Você precisa aprender coisas novas no seu trabalho?', inverted: false },
  { domain: 'Demandas Emocionais', text: 'O seu trabalho exige que você esconda emoções?', inverted: true },
  { domain: 'Demandas Emocionais', text: 'Você lida com situações emocionalmente difíceis?', inverted: true },
  { domain: 'Demandas Emocionais', text: 'O seu trabalho afeta o seu estado emocional?', inverted: true },
  { domain: 'Influência no Trabalho', text: 'Você tem influência sobre como realiza o seu trabalho?', inverted: false },
  { domain: 'Influência no Trabalho', text: 'Você pode decidir a ordem das suas tarefas?', inverted: false },
  { domain: 'Influência no Trabalho', text: 'Você pode decidir o seu ritmo de trabalho?', inverted: false },
  { domain: 'Possibilidades de Desenvolvimento', text: 'Você tem a possibilidade de aprender coisas novas?', inverted: false },
  { domain: 'Possibilidades de Desenvolvimento', text: 'Seu trabalho permite desenvolver suas habilidades?', inverted: false },
  { domain: 'Possibilidades de Desenvolvimento', text: 'Você sente que seu trabalho contribui para seu crescimento pessoal?', inverted: false },
  { domain: 'Sentido do Trabalho', text: 'Você sente que o seu trabalho é importante?', inverted: false },
  { domain: 'Sentido do Trabalho', text: 'Você sente orgulho do seu trabalho?', inverted: false },
  { domain: 'Sentido do Trabalho', text: 'O seu trabalho faz sentido para você?', inverted: false },
  { domain: 'Clareza de Papel', text: 'Você sabe exatamente quais são suas responsabilidades?', inverted: false },
  { domain: 'Clareza de Papel', text: 'Você sabe quais decisões pode tomar sozinho(a)?', inverted: false },
  { domain: 'Clareza de Papel', text: 'As tarefas atribuídas a você são claras?', inverted: false },
  { domain: 'Conflitos de Papel', text: 'Você recebe tarefas contraditórias?', inverted: true },
  { domain: 'Conflitos de Papel', text: 'É necessário fazer coisas que você acha desnecessárias?', inverted: true },
  { domain: 'Conflitos de Papel', text: 'É necessário negligenciar uma tarefa para cumprir outra?', inverted: true },
  { domain: 'Previsibilidade', text: 'Você é informado com antecedência sobre mudanças que afetam seu trabalho?', inverted: false },
  { domain: 'Previsibilidade', text: 'Você sabe o que acontecerá em seu trabalho nas próximas semanas?', inverted: false },
  { domain: 'Previsibilidade', text: 'As mudanças na empresa são comunicadas claramente?', inverted: false },
  { domain: 'Reconhecimento e Recompensa', text: 'Você recebe reconhecimento suficiente pelo seu trabalho?', inverted: false },
  { domain: 'Reconhecimento e Recompensa', text: 'Seu trabalho é valorizado pela chefia?', inverted: false },
  { domain: 'Reconhecimento e Recompensa', text: 'Seu trabalho é reconhecido pelos colegas?', inverted: false },
  { domain: 'Apoio Social - Chefia', text: 'Você recebe ajuda da sua chefia quando necessário?', inverted: false },
  { domain: 'Apoio Social - Chefia', text: 'Sua chefia se interessa pelo seu bem-estar?', inverted: false },
  { domain: 'Apoio Social - Chefia', text: 'A chefia trata os trabalhadores com respeito?', inverted: false },
  { domain: 'Apoio Social - Colegas', text: 'Você recebe apoio dos colegas?', inverted: false },
  { domain: 'Apoio Social - Colegas', text: 'Seus colegas estão dispostos a ouvir seus problemas relacionados ao trabalho?', inverted: false },
  { domain: 'Apoio Social - Colegas', text: 'O ambiente entre os colegas é agradável?', inverted: false },
  { domain: 'Feedback sobre o Trabalho', text: 'Você recebe retorno sobre o seu desempenho?', inverted: false },
  { domain: 'Feedback sobre o Trabalho', text: 'Você sabe se está realizando um bom trabalho?', inverted: false },
  { domain: 'Feedback sobre o Trabalho', text: 'O feedback que você recebe é útil?', inverted: false },
  { domain: 'Qualidade de Liderança', text: 'Sua chefia é eficiente na gestão do setor?', inverted: false },
  { domain: 'Qualidade de Liderança', text: 'Sua chefia lida bem com conflitos?', inverted: false },
  { domain: 'Qualidade de Liderança', text: 'Sua chefia comunica bem as decisões?', inverted: false },
  { domain: 'Justiça Organizacional', text: 'Você é tratado de forma justa no trabalho?', inverted: false },
  { domain: 'Justiça Organizacional', text: 'As decisões são tomadas com imparcialidade?', inverted: false },
  { domain: 'Justiça Organizacional', text: 'Os procedimentos da empresa são justos?', inverted: false },
  { domain: 'Comprometimento com o Local de Trabalho', text: 'Você se sente comprometido com sua organização?', inverted: false },
  { domain: 'Comprometimento com o Local de Trabalho', text: 'Você recomendaria sua empresa como um bom lugar para trabalhar?', inverted: false },
  { domain: 'Comprometimento com o Local de Trabalho', text: 'Você sente orgulho de pertencer à sua empresa?', inverted: false },
  { domain: 'Insegurança no Trabalho', text: 'Você teme perder o emprego?', inverted: true },
  { domain: 'Insegurança no Trabalho', text: 'Você acha que será transferido contra sua vontade?', inverted: true },
  { domain: 'Insegurança no Trabalho', text: 'Há risco de reestruturação no seu setor?', inverted: true },
  { domain: 'Conflito Trabalho-Família', text: 'Seu trabalho afeta negativamente sua vida pessoal?', inverted: true },
  { domain: 'Conflito Trabalho-Família', text: 'Você chega em casa cansado(a) demais para atividades pessoais?', inverted: true },
  { domain: 'Conflito Trabalho-Família', text: 'Suas responsabilidades familiares afetam seu desempenho no trabalho?', inverted: true },
  { domain: 'Saúde e Bem-Estar', text: 'Você sente-se esgotado(a) após o trabalho?', inverted: true },
  { domain: 'Saúde e Bem-Estar', text: 'Você dorme bem em noites úteis?', inverted: false },
  { domain: 'Saúde e Bem-Estar', text: 'Você tem dores físicas relacionadas ao trabalho?', inverted: true },
  { domain: 'Presenteísmo', text: 'Você continua trabalhando mesmo doente?', inverted: true },
  { domain: 'Presenteísmo', text: 'Você já trabalhou mesmo sem condições físicas ou emocionais?', inverted: true },
  { domain: 'Presenteísmo', text: 'Você sente que não pode faltar ao trabalho mesmo se precisar?', inverted: true },
];

export const RESPONSE_OPTIONS = [
  { value: 0, label: 'Nunca' },
  { value: 1, label: 'Raramente' },
  { value: 2, label: 'Às vezes' },
  { value: 3, label: 'Sempre' },
  { value: 4, label: 'Frequentemente' },
];
